import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import type { SessionState, BuildResult } from "./types";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, "../../");
const agentsMdPath = path.join(projectRoot, "AGENTS.md");

export function readAgentsMd(): string {
  if (!fs.existsSync(agentsMdPath)) return "";
  return fs.readFileSync(agentsMdPath, "utf-8");
}

export function updateAgentsMd(buildResult: BuildResult | null): boolean {
  if (!fs.existsSync(agentsMdPath)) return false;

  let content = fs.readFileSync(agentsMdPath, "utf-8");

  const stateLine = findOrCreateSection(content, "## Build Status");
  const buildStatus = buildResult
    ? `Build: ${buildResult.success ? "✅ PASS" : "❌ FAIL"} (${(buildResult.durationMs / 1000).toFixed(1)}s)`
    : "Build: unknown";
  const timestamp = new Date().toISOString().split("T")[0];

  content = content.replace(
    /## Build Status[\s\S]*?(?=\n## |$)/,
    `## Build Status\n- **Date:** ${timestamp}\n- **${buildStatus}**\n- **Errors:** ${buildResult?.errors.length ?? 0}\n- **Warnings:** ${buildResult?.warnings.length ?? 0}\n\n`
  );

  if (!content.includes("## Build Status")) {
    content += `\n## Build Status\n- **Date:** ${timestamp}\n- **${buildStatus}**\n- **Errors:** ${buildResult?.errors.length ?? 0}\n- **Warnings:** ${buildResult?.warnings.length ?? 0}\n`;
  }

  fs.writeFileSync(agentsMdPath, content, "utf-8");
  return true;
}

function findOrCreateSection(content: string, sectionTitle: string): number {
  const lines = content.split("\n");
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].startsWith(sectionTitle)) return i;
  }
  return -1;
}

export function generateSessionReport(state: SessionState): string {
  const lines: string[] = [
    "# Session Report",
    `- **Date:** ${new Date().toISOString().split("T")[0]}`,
    `- **Total pages:** ${state.totalPages}`,
    `- **Implemented:** ${state.implementedPages}`,
    `- **Placeholders:** ${state.placeholderPages}`,
    `- **Generated by engine:** ${state.generatedPages}`,
    `- **Hand-built:** ${state.handBuiltPages}`,
    "",
  ];

  if (state.patternsFound.length > 0) {
    lines.push("## Patterns Detected");
    for (const p of state.patternsFound) {
      lines.push(`- [${p.confidence > 0.8 ? "HIGH" : "MEDIUM"}] ${p.description}`);
    }
    lines.push("");
  }

  if (state.lastBuild) {
    lines.push("## Build");
    lines.push(`- Status: ${state.lastBuild.success ? "✅ PASS" : "❌ FAIL"}`);
    lines.push(`- Duration: ${(state.lastBuild.durationMs / 1000).toFixed(1)}s`);
    if (state.lastBuild.errors.length > 0) {
      lines.push("- Errors:");
      for (const e of state.lastBuild.errors) {
        lines.push(`  - ${e.file}:${e.line || "?"} ${e.message}`);
      }
    }
    lines.push("");
  }

  return lines.join("\n");
}
