import * as fs from "fs";
import * as path from "path";
import { createHash } from "crypto";
import { fileURLToPath } from "url";
import type { EngineState, PageConfig, GeneratedFile } from "./types";
import { generateAstroPage } from "./templates/astro-page";
import { generateAdminCrudComponent } from "./templates/admin-crud-component";
import { generateAdminReadonlyComponent } from "./templates/admin-readonly-component";
import { generateAdminDashboardComponent } from "./templates/admin-dashboard-component";
import { generateAdminOperationsComponent } from "./templates/admin-operations-component";
import { generateAdminCrudApi } from "./templates/admin-api";
import { generatePanelCrudComponent } from "./templates/panel-crud-component";
import { generatePanelApi } from "./templates/panel-api";
import { generateZodSchema } from "./templates/zod-schema";
import { generatePlaceholderComponent } from "./templates/placeholder-component";
import { generatePlaceholderApi } from "./templates/placeholder-api";
import { writeFile } from "./lib/file-writer";
import type { WriteMode } from "./lib/file-writer";
import { trigger as hookTrigger } from "../governance/hook-broker";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const CACHE_PATH = path.resolve(__dirname, "../../.generated-hashes.json");

const WATERMARK = `/**
 * Generated by Harness ENGINEERING
 * Created by Shaman / Roberth Silva — https://github.com/shaman2527
 * Stack-agnostic tools for AI-assisted software engineering.
 */\n
`;

export interface GenerateOptions {
  writeMode?: WriteMode;
  dryRun?: boolean;
  filterPages?: string[];
  verbose?: boolean;
  incremental?: boolean;
}

function loadHashCache(): Record<string, string> {
  try {
    return JSON.parse(fs.readFileSync(CACHE_PATH, "utf-8"));
  } catch {
    return {};
  }
}

function saveHashCache(cache: Record<string, string>): void {
  fs.writeFileSync(CACHE_PATH, JSON.stringify(cache, null, 2), "utf-8");
}

function contentHash(content: string, pageConfig: PageConfig): string {
  return createHash("sha256").update(content).update(JSON.stringify(pageConfig)).digest("hex").slice(0, 16);
}

function isAdminLayout(page: PageConfig): boolean {
  return page.layout === "AdminLayout";
}

function generateComponent(page: PageConfig): string {
  if (isAdminLayout(page)) {
    if (page.pageType === "readonly") return generateAdminReadonlyComponent(page);
    if (page.pageType === "crud") return generateAdminCrudComponent(page);
    if (page.pageType === "dashboard") return generateAdminDashboardComponent(page);
    if (page.pageType === "operations") return generateAdminOperationsComponent(page);
    return generatePlaceholderComponent(page);
  }
  // PanelLayout
  if (page.pageType === "crud" || page.pageType === "readonly") return generatePanelCrudComponent(page);
  return generatePlaceholderComponent(page);
}

function generateApi(page: PageConfig): string {
  if (isAdminLayout(page)) {
    if (page.pageType === "crud" || page.pageType === "readonly" || page.pageType === "dashboard" || page.pageType === "operations") return generateAdminCrudApi(page);
    return generatePlaceholderApi(page);
  }
  // PanelLayout
  return generatePanelApi(page);
}

function generateSchema(page: PageConfig): string | null {
  if (page.pageType === "crud" && page.formFields.length > 0) {
    return generateZodSchema(page);
  }
  return null;
}

export function generatePage(page: PageConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  const astroContent = generateAstroPage(page);
  files.push({
    path: `src/pages/${page.route}.astro`,
    content: astroContent,
  });

  const componentDir = page.layout === "AdminLayout" ? "admin" : "panel";
  const componentContent = generateComponent(page);
  files.push({
    path: `src/components/${componentDir}/${page.componentName}.tsx`,
    content: WATERMARK + componentContent,
  });

  const apiContent = generateApi(page);
  files.push({
    path: `src/pages/api/${page.apiEndpoint}.ts`,
    content: WATERMARK + apiContent,
  });

  const schemaContent = generateSchema(page);
  if (schemaContent) {
    files.push({
      path: `src/lib/schemas/${page.table}.ts`,
      content: WATERMARK + schemaContent,
    });
  }

  return files;
}

export function generateAll(pages: PageConfig[], options: GenerateOptions = {}): EngineState {
  const state: EngineState = {
    pages,
    generated: [],
    errors: [],
  };

  const { writeMode = "overwrite", dryRun = false, filterPages, verbose = false, incremental = false } = options;

  const hashCache = incremental ? loadHashCache() : {};
  let cacheDirty = false;

  const pagesToGenerate = filterPages
    ? pages.filter(p => filterPages.includes(p.route) || filterPages.includes(p.componentName))
    : pages;

  for (const page of pagesToGenerate) {
    if (verbose || filterPages) console.log(`\n=== Generating ${page.route} (${page.title}) ===`);

    try {
      const files = generatePage(page);
      for (const file of files) {
        if (dryRun) {
          console.log(`  📝 [dry-run] ${file.path} (${file.content.length} bytes)`);
          continue;
        }

        // Incremental: skip if content hash matches cached hash
        if (incremental) {
          const h = contentHash(file.content, page);
          if (hashCache[file.path] === h) {
            if (verbose) console.log(`  ⏭️  ${file.path} (unchanged, skipped)`);
            continue;
          }
          hashCache[file.path] = h;
          cacheDirty = true;
        }

        const written = writeFile(file, writeMode);
        if (written) {
          state.generated.push(file);
        }

        hookTrigger("POST_EXECUTE", {
          sender: "code-generator",
          target: file.path.endsWith(".ts") && !file.path.includes("components") ? "api" : "component",
          data: { page: { ...page }, filePath: file.path, content: file.content },
        }).catch(() => {});
      }
      if (!verbose && !filterPages) console.log(`  ✅ ${page.route} complete`);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`  ❌ ${page.route}: ${msg}`);
      state.errors.push({ page: page.route, error: msg });

      hookTrigger("ON_FAILURE", {
        sender: "code-generator",
        target: page.route,
        data: { page: { ...page }, errors: [{ file: page.route, message: msg }] },
      }).catch(() => {});
    }
  }

  if (incremental && cacheDirty) saveHashCache(hashCache);

  return state;
}
